/* Generated By:JJTree&JavaCC: Do not edit this line. HLConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LESS = 5;
  /** RegularExpression Id. */
  int LESSEQ = 6;
  /** RegularExpression Id. */
  int GREATER = 7;
  /** RegularExpression Id. */
  int GREATEQ = 8;
  /** RegularExpression Id. */
  int EQUAL = 9;
  /** RegularExpression Id. */
  int NOTEQ = 10;
  /** RegularExpression Id. */
  int PLUS = 11;
  /** RegularExpression Id. */
  int MINUS = 12;
  /** RegularExpression Id. */
  int TIMES = 13;
  /** RegularExpression Id. */
  int DIV = 14;
  /** RegularExpression Id. */
  int MOD = 15;
  /** RegularExpression Id. */
  int AND = 16;
  /** RegularExpression Id. */
  int VBAR = 17;
  /** RegularExpression Id. */
  int NOT = 18;
  /** RegularExpression Id. */
  int ASSIGN = 19;
  /** RegularExpression Id. */
  int LROUND = 20;
  /** RegularExpression Id. */
  int LCURLY = 21;
  /** RegularExpression Id. */
  int LSQUARE = 22;
  /** RegularExpression Id. */
  int RROUND = 23;
  /** RegularExpression Id. */
  int RCURLY = 24;
  /** RegularExpression Id. */
  int RSQUARE = 25;
  /** RegularExpression Id. */
  int COMMA = 26;
  /** RegularExpression Id. */
  int SEMICOL = 27;
  /** RegularExpression Id. */
  int TRUE = 28;
  /** RegularExpression Id. */
  int FALSE = 29;
  /** RegularExpression Id. */
  int DO = 30;
  /** RegularExpression Id. */
  int ELIF = 31;
  /** RegularExpression Id. */
  int ELSE = 32;
  /** RegularExpression Id. */
  int END = 33;
  /** RegularExpression Id. */
  int FI = 34;
  /** RegularExpression Id. */
  int FOR = 35;
  /** RegularExpression Id. */
  int FUNCTION = 36;
  /** RegularExpression Id. */
  int IF = 37;
  /** RegularExpression Id. */
  int IN = 38;
  /** RegularExpression Id. */
  int ISIN = 39;
  /** RegularExpression Id. */
  int NOTIN = 40;
  /** RegularExpression Id. */
  int PRINT = 41;
  /** RegularExpression Id. */
  int PRINTLN = 42;
  /** RegularExpression Id. */
  int RETURN = 43;
  /** RegularExpression Id. */
  int THEN = 44;
  /** RegularExpression Id. */
  int VAR = 45;
  /** RegularExpression Id. */
  int WHILE = 46;
  /** RegularExpression Id. */
  int DIGIT = 47;
  /** RegularExpression Id. */
  int LOWER = 48;
  /** RegularExpression Id. */
  int UPPER = 49;
  /** RegularExpression Id. */
  int LETTER = 50;
  /** RegularExpression Id. */
  int NUMBER = 51;
  /** RegularExpression Id. */
  int IDNUM = 52;
  /** RegularExpression Id. */
  int IDSET = 53;
  /** RegularExpression Id. */
  int IDBOOL = 54;
  /** RegularExpression Id. */
  int STRING = 55;
  /** RegularExpression Id. */
  int COMMENT_SINGLE = 56;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "\"=\"",
    "\"(\"",
    "\"{\"",
    "\"[\"",
    "\")\"",
    "\"}\"",
    "\"]\"",
    "\",\"",
    "\";\"",
    "\"#1\"",
    "\"#0\"",
    "\"DO\"",
    "\"ELIF\"",
    "\"ELSE\"",
    "\"END\"",
    "\"FI\"",
    "\"FOR\"",
    "\"FUNCTION\"",
    "\"IF\"",
    "\"IN\"",
    "\"=IN\"",
    "\"!IN\"",
    "\"PRINT\"",
    "\"PRINTLN\"",
    "\"RETURN\"",
    "\"THEN\"",
    "\"VAR\"",
    "\"WHILE\"",
    "<DIGIT>",
    "<LOWER>",
    "<UPPER>",
    "<LETTER>",
    "<NUMBER>",
    "<IDNUM>",
    "<IDSET>",
    "<IDBOOL>",
    "<STRING>",
    "<COMMENT_SINGLE>",
  };

}
