/* Generated By:JJTree: Do not edit this line. ASTAbsolute_value.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAbsolute_value extends SimpleNode {
  public ASTAbsolute_value(int id) {
    super(id);
  }

  public ASTAbsolute_value(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5683b8c20780490f474d29dff2e94507 (do not edit this line) */
