/* Generated By:JJTree: Do not edit this line. ASTexp_list.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTexp_list extends SimpleNode {
  public ASTexp_list(int id) {
    super(id);
  }

  public ASTexp_list(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bd9a7798265e310b4d8a5429fdd7e668 (do not edit this line) */
