/* Generated By:JJTree: Do not edit this line. ASTEQUAL.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEQUAL extends SimpleNode {
  public ASTEQUAL(int id) {
    super(id);
  }

  public ASTEQUAL(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=de7c56c9a5e17a7913f4d47a850729bf (do not edit this line) */
