/* Generated By:JJTree: Do not edit this line. ASTFALSE.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFALSE extends SimpleNode {
  public ASTFALSE(int id) {
    super(id);
  }

  public ASTFALSE(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=88ea7ec0a16d532aa8b00dbb0394d67c (do not edit this line) */
