/* Generated By:JJTree: Do not edit this line. ASTGREATEQ.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTGREATEQ extends SimpleNode {
  public ASTGREATEQ(int id) {
    super(id);
  }

  public ASTGREATEQ(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f4887e163fb5ae577d20ac7ef6a72274 (do not edit this line) */
