/* Generated By:JJTree: Do not edit this line. ASTNOTIN.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNOTIN extends SimpleNode {
  public ASTNOTIN(int id) {
    super(id);
  }

  public ASTNOTIN(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d6bc23c5bfc34921c388a4ad54f84725 (do not edit this line) */
