/* Generated By:JJTree: Do not edit this line. ASTNOTEQ.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNOTEQ extends SimpleNode {
  public ASTNOTEQ(int id) {
    super(id);
  }

  public ASTNOTEQ(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5e7531ce7c5b674305ebbacf901176e7 (do not edit this line) */
