/* Generated By:JJTree: Do not edit this line. ASTTRUE.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTRUE extends SimpleNode {
  public ASTTRUE(int id) {
    super(id);
  }

  public ASTTRUE(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c663bd669603460a0b22ef3fba946ad4 (do not edit this line) */
