/* Generated By:JJTree: Do not edit this line. ASTtypebool.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTtypebool extends SimpleNode {
  public ASTtypebool(int id) {
    super(id);
  }

  public ASTtypebool(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1d00e8ce0f8ef0e51dbee54a95200078 (do not edit this line) */
