/* Generated By:JJTree: Do not edit this line. ASTvalue_list.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTvalue_list extends SimpleNode {
  public ASTvalue_list(int id) {
    super(id);
  }

  public ASTvalue_list(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a540f3d33b991915fe5c0f3f9dde5848 (do not edit this line) */
