/* Generated By:JavaCC: Do not edit this line. HLTreeConstants.java Version 7.0.9 */
public interface HLTreeConstants
{
  public int JJTVOID = 0;
  public int JJTBODY = 1;
  public int JJTCLAUSE = 2;
  public int JJTVAR_DECL = 3;
  public int JJTFN_DECL = 4;
  public int JJTIDENT_LIST = 5;
  public int JJTFN_CALL = 6;
  public int JJTBOOLEAN_CALL = 7;
  public int JJTVALUE_LIST = 8;
  public int JJTRETURN = 9;
  public int JJTASSIGN = 10;
  public int JJTPRINT = 11;
  public int JJTPRINTLN = 12;
  public int JJTPRINT_LIST = 13;
  public int JJTIF = 14;
  public int JJTNULL = 15;
  public int JJTFOR = 16;
  public int JJTEXP_LIST = 17;
  public int JJTWHILE = 18;
  public int JJTOR = 19;
  public int JJTAND = 20;
  public int JJTNOT = 21;
  public int JJTTRUE = 22;
  public int JJTFALSE = 23;
  public int JJTCOMPARISON = 24;
  public int JJTLESS = 25;
  public int JJTLESSEQ = 26;
  public int JJTGREATER = 27;
  public int JJTGREATEQ = 28;
  public int JJTEQUAL = 29;
  public int JJTNOTEQ = 30;
  public int JJTISIN = 31;
  public int JJTNOTIN = 32;
  public int JJTSUM = 33;
  public int JJTNEG = 34;
  public int JJTPOS = 35;
  public int JJTMUL = 36;
  public int JJTDIV = 37;
  public int JJTMOD = 38;
  public int JJTABSOLUTE_VALUE = 39;
  public int JJTINTERVAL = 40;
  public int JJTSET_FORMER = 41;
  public int JJTSET = 42;
  public int JJTIDENTIFIER = 43;
  public int JJTTYPENUM = 44;
  public int JJTTYPESET = 45;
  public int JJTTYPEBOOL = 46;
  public int JJTNUMBER = 47;
  public int JJTSTRING = 48;


  public String[] jjtNodeName = {
    "void",
    "body",
    "clause",
    "var_decl",
    "fn_decl",
    "ident_list",
    "fn_call",
    "boolean_call",
    "value_list",
    "Return",
    "Assign",
    "Print",
    "Println",
    "print_list",
    "If",
    "NULL",
    "For",
    "exp_list",
    "While",
    "or",
    "and",
    "not",
    "TRUE",
    "FALSE",
    "comparison",
    "LESS",
    "LESSEQ",
    "GREATER",
    "GREATEQ",
    "EQUAL",
    "NOTEQ",
    "ISIN",
    "NOTIN",
    "sum",
    "neg",
    "pos",
    "mul",
    "div",
    "mod",
    "Absolute_value",
    "interval",
    "set_former",
    "set",
    "identifier",
    "typenum",
    "typeset",
    "typebool",
    "number",
    "string",
  };
}
/* JavaCC - OriginalChecksum=db47116f15e52376155ea500aa38511e (do not edit this line) */
